### ISSUE TITLE
Ability to send confirmation emails for sessions

### ISSUE THREAD

**Issue by trystant** [fabbballin/thinkfulmentor#1]
Hi, 

I like what I've seen of this so far. One feature request would be to add the ability to send confirmation emails before each session.  Thanks.

**Comment by fabioaanthony** [comment]
Hi Mark, Thanks for your feedback! The main purpose of this app is to automate invoicing as per Thinkful's guidelines. I feel that feature would be out of scope for this app and should be something handled by your scheduling tool, Thinkful (main app) or your calendar.
